# Create AzureAD 'AV Administrator' role information
$displayName = "Azure AV Administrator"
$description = "Grants some device capabilities, and the ability to read Bitlocker keys, as well as general read rights."
$templateId = (New-Guid).Guid
 
# Set of permissions to grant
$allowedResourceAction =
@(
    "microsoft.directory/bitlockerKeys/key/read",
    "microsoft.directory/devices/create",
    "microsoft.directory/devices/delete",
    "microsoft.directory/devices/disable",
    "microsoft.directory/devices/enable",
    "microsoft.directory/devices/basic/update",
    "microsoft.directory/devices/registeredOwners/update",
    "microsoft.directory/devices/registeredUsers/update",
    "microsoft.directory/deviceManagementPolicies/standard/read",
    "microsoft.directory/deviceRegistrationPolicy/standard/read",
    "microsoft.directory/administrativeUnits/standard/read",
    "microsoft.directory/administrativeUnits/members/read",
    "microsoft.directory/applications/standard/read",
    "microsoft.directory/applications/owners/read",
    "microsoft.directory/applications/policies/read",
    "microsoft.directory/contacts/standard/read",
    "microsoft.directory/contacts/memberOf/read",
    "microsoft.directory/contracts/standard/read",
    "microsoft.directory/devices/standard/read",
    "microsoft.directory/devices/memberOf/read",
    "microsoft.directory/devices/registeredOwners/read",
    "microsoft.directory/devices/registeredUsers/read",
    "microsoft.directory/directoryRoles/standard/read",
    "microsoft.directory/directoryRoles/eligibleMembers/read",
    "microsoft.directory/directoryRoles/members/read",
    "microsoft.directory/domains/standard/read",
    "microsoft.directory/groups/standard/read",
    "microsoft.directory/groups/appRoleAssignments/read",
    "microsoft.directory/groups/memberOf/read",
    "microsoft.directory/groups/members/read",
    "microsoft.directory/groups/owners/read",
    "microsoft.directory/groups/settings/read",
    "microsoft.directory/groupSettings/standard/read",
    "microsoft.directory/groupSettingTemplates/standard/read",
    "microsoft.directory/oAuth2PermissionGrants/standard/read",
    "microsoft.directory/organization/standard/read",
    "microsoft.directory/organization/trustedCAsForPasswordlessAuth/read",
    "microsoft.directory/applicationPolicies/standard/read",
    "microsoft.directory/roleAssignments/standard/read",
    "microsoft.directory/roleDefinitions/standard/read",
    "microsoft.directory/servicePrincipals/appRoleAssignedTo/read",
    "microsoft.directory/servicePrincipals/appRoleAssignments/read",
    "microsoft.directory/servicePrincipals/standard/read",
    "microsoft.directory/servicePrincipals/memberOf/read",
    "microsoft.directory/servicePrincipals/oAuth2PermissionGrants/read",
    "microsoft.directory/servicePrincipals/owners/read",
    "microsoft.directory/servicePrincipals/ownedObjects/read",
    "microsoft.directory/servicePrincipals/policies/read",
    "microsoft.directory/subscribedSkus/standard/read",
    "microsoft.directory/users/standard/read",
    "microsoft.directory/users/appRoleAssignments/read",
    "microsoft.directory/users/deviceForResourceAccount/read",
    "microsoft.directory/users/directReports/read",
    "microsoft.directory/users/licenseDetails/read",
    "microsoft.directory/users/manager/read",
    "microsoft.directory/users/memberOf/read",
    "microsoft.directory/users/oAuth2PermissionGrants/read",
    "microsoft.directory/users/ownedDevices/read",
    "microsoft.directory/users/ownedObjects/read",
    "microsoft.directory/users/photo/read",
    "microsoft.directory/users/registeredDevices/read",
    "microsoft.directory/users/scopedRoleMemberOf/read"
)
$rolePermissions = @{'allowedResourceActions'= $allowedResourceAction}
 
# Create new custom admin role
$customAdmin = New-AzureADMSRoleDefinition -RolePermissions $rolePermissions -DisplayName $displayName -Description $description -TemplateId $templateId -IsEnabled $true