# Install and import the relevant module
Function Install-RequiredModule {
    [CmdletBinding()]
    param (
        [Parameter()]
        [string]
        $Name
    )

    Write-Verbose "Grabbing the version of $Name from the gallery."
    $GalleryModuleVersion = (Find-Module $Name).Version
    Write-Verbose 'Gallery version is:'
    Write-Verbose $GalleryModuleVersion
    Write-Verbose "Grabbing the version of $Name that is installed (if any)."
    $InstalledModuleVersion = (Get-InstalledModule $Name -ErrorAction SilentlyContinue).Version
    If ($null -eq $InstalledModuleVersion) {
        $InstalledModuleVersion = 'Not installed.'
    }
    Write-Verbose 'Installed version is:'
    Write-Verbose $InstalledModuleVersion
    Write-Verbose 'Comparing the two to see if the gallery is newer.'
    If (!($InstalledModuleVersion -ge $GalleryModuleVersion)) {
        Write-Verbose 'Gallery version is newer, or its not installed.'
        Write-Verbose "Installing the $Name module."
        Install-Module $Name -Force -AllowClobber
        Write-Verbose "Importing the $Name module."
        Import-Module $Name
    }
    Else {
        Write-Verbose "$Name module is current."
    }
}
Install-RequiredModule Microsoft.Graph.DeviceManagement.Administration -Verbose

# Select beta Graph profile
Select-MgProfile -Name Beta

# Connect to Microsoft Graph, with the specified scope
# Keep in mind, the account running this must have the appropriate permissions6
Connect-MgGraph -Scopes DeviceManagementRBAC.ReadWrite.All

# Set the URI path
$uri = "https://graph.microsoft.com/beta/deviceManagement/roleDefinitions/"

# Create the json payload
$json = @'
	{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#deviceManagement/roleDefinitions/$entity",
    "@odata.type": "#microsoft.graph.deviceAndAppManagementRoleDefinition",
    "displayName": "Help Desk Operators - Tier 1 Test",
    "description": "Help Desk Operators - Tier 1 can perform remote tasks on users and devices and can assign applications or policies to users or devices. This is a clone of the built-in \"Help Desk Operators\" role, minus some permissions such as wipe (all kinds), and application deployments.",
    "isBuiltInRoleDefinition": false,
    "isBuiltIn": false,
    "roleScopeTagIds": [],
    "permissions": [
        {
            "actions": [
                "Microsoft.Intune_AndroidSync_Read",
                "Microsoft.Intune_MobileApps_Read",
                "Microsoft.Intune_ManagedApps_Read",
                "Microsoft.Intune_PolicySets_Read",
                "Microsoft.Intune_Reports_Read",
                "Microsoft.Intune_Customization_Read",
                "Microsoft.Intune_Organization_Read",
                "Microsoft.Intune_ManagedDevices_Read",
                "Microsoft.Intune_RemoteTasks_GetFileVaultKey",
                "Microsoft.Intune_RemoteTasks_WindowsDefender",
                "Microsoft.Intune_RemoteTasks_ManageSharedDeviceUsers",
                "Microsoft.Intune_DeviceCompliancePolices_Read",
                "Microsoft.Intune_AppleEnrollmentProfiles_Read",
                "Microsoft.Intune_PartnerDeviceManagement_Read",
                "Microsoft.Intune_EnrollmentProgramToken_Read",
                "Microsoft.Intune_RemoteTasks_DisableLostMode",
                "Microsoft.Intune_RemoteTasks_RotateBitLockerKeys",
                "Microsoft.Intune_Roles_Read",
                "Microsoft.Intune_RemoteAssistance_ViewReports",
                "Microsoft.Intune_DeviceCompliancePolices_ViewReports",
                "Microsoft.Intune_ChromebookSync_Read",
                "Microsoft.Intune_RemoteTasks_ShutDown",
                "Microsoft.Intune_DerivedCredentials_Read",
                "Microsoft.Intune_RemoteTasks_LocateDevice",
                "Microsoft.Intune_RemoteTasks_RemoteLock",
                "Microsoft.Intune_ManagedDevices_SetPrimaryUser",
                "Microsoft.Intune_SecurityTasks_Read",
                "Microsoft.Intune_RemoteTasks_EnableWindowsIntuneAgent",
                "Microsoft.Intune_TelecomExpenses_Read",
                "Microsoft.Intune_MobileThreatDefense_Read",
                "Microsoft.Intune_EndpointProtection_Read",
                "Microsoft.Intune_AppleDeviceSerialNumbers_Read",
                "Microsoft.Intune_EndpointAnalytics_Read",
                "Microsoft.Intune_RemoteTasks_ResetPasscode",
                "Microsoft.Intune_RemoteTasks_ConfigurationManagerAction",
                "Microsoft.Intune_CloudAttach_Collections",
                "Microsoft.Intune_CloudAttach_ResourceExplorer",
                "Microsoft.Intune_CloudAttach_Timeline",
                "Microsoft.Intune_DeviceConfigurations_Read",
                "Microsoft.Intune_CloudAttach_Scripts",
                "Microsoft.Intune_CloudAttach_SoftwareUpdates",
                "Microsoft.Intune_OrganizationalMessages_Read",
                "Microsoft.Intune_RemoteTasks_OnDemandProactiveRemediation",
                "Microsoft.Intune_MultiAdminApproval_ReadAccessPolicy",
                "Microsoft.Intune_EpmPolicy_ViewReports",
                "Microsoft.Intune_TermsAndConditions_Read",
                "Microsoft.Intune_SecurityBaselines_Read",
                "Microsoft.Intune_AssignmentFilter_Read",
                "Microsoft.Intune_CertificateConnector_Read",
                "Microsoft.Intune_RemoteTasks_EnableLostMode",
                "Microsoft.Intune_MicrosoftDefenderATP_Read",
                "Microsoft.Intune_RemoteTasks_RotateLocalAdminPassword",
                "Microsoft.Intune_EpmPolicy_Read",
                "Microsoft.Intune_DeviceConfigurations_ViewReports",
                "Microsoft.Intune_CorporateDeviceIdentifiers_Read",
                "Microsoft.Intune_MicrosoftTunnelGateway_Read",
                "Microsoft.Intune_RemoteTasks_DeviceLogs",
                "Microsoft.Intune_RemoteTasks_PlayLostModeSound",
                "Microsoft.Intune_RemoteTasks_RebootNow",
                "Microsoft.Intune_RemoteTasks_RotateFileVaultKey",
                "Microsoft.Intune_RemoteTasks_SyncDevice",
                "Microsoft.Intune_MicrosoftStoreForBusiness_Read",
                "Microsoft.Intune_ManagedGooglePlay_Read",
                "Microsoft.Intune_AndroidFota_Read",
                "Microsoft.Intune_QuietTimePolicies_Read",
                "Microsoft.Intune_CloudAttach_CMPivot",
                "Microsoft.Intune_WindowsEnterpriseCertificate_Read",
                "Microsoft.Intune_MobileApps_ViewReports",
                "Microsoft.Intune_RemoteAssistance_Read",
                "Microsoft.Intune_DeviceEnrollmentManagers_Read",
                "Microsoft.Intune_ManagedDevices_ViewReports",
                "Microsoft.Intune_QuietTimePolicies_ViewReports",
                "Microsoft.Intune_CloudAttach_ClientDetails",
                "Microsoft.Intune_CloudAttach_ApplicationActions",
                "Microsoft.Intune_CloudAttach_Applications",
                "Microsoft.Intune_CloudAttach_EnrollNow",
            ],
            "resourceActions": [
                {
                    "allowedResourceActions": [
                        "Microsoft.Intune_AndroidSync_Read",
                        "Microsoft.Intune_MobileApps_Read",
                        "Microsoft.Intune_ManagedApps_Read",
                        "Microsoft.Intune_PolicySets_Read",
                        "Microsoft.Intune_Reports_Read",
                        "Microsoft.Intune_Customization_Read",
                        "Microsoft.Intune_Organization_Read",
                        "Microsoft.Intune_ManagedDevices_Read",
                        "Microsoft.Intune_RemoteTasks_GetFileVaultKey",
                        "Microsoft.Intune_RemoteTasks_WindowsDefender",
                        "Microsoft.Intune_RemoteTasks_ManageSharedDeviceUsers",
                        "Microsoft.Intune_DeviceCompliancePolices_Read",
                        "Microsoft.Intune_AppleEnrollmentProfiles_Read",
                        "Microsoft.Intune_PartnerDeviceManagement_Read",
                        "Microsoft.Intune_EnrollmentProgramToken_Read",
                        "Microsoft.Intune_RemoteTasks_DisableLostMode",
                        "Microsoft.Intune_RemoteTasks_RotateBitLockerKeys",
                        "Microsoft.Intune_Roles_Read",
                        "Microsoft.Intune_RemoteAssistance_ViewReports",
                        "Microsoft.Intune_DeviceCompliancePolices_ViewReports",
                        "Microsoft.Intune_ChromebookSync_Read",
                        "Microsoft.Intune_RemoteTasks_ShutDown",
                        "Microsoft.Intune_DerivedCredentials_Read",
                        "Microsoft.Intune_RemoteTasks_LocateDevice",
                        "Microsoft.Intune_RemoteTasks_RemoteLock",
                        "Microsoft.Intune_ManagedDevices_SetPrimaryUser",
                        "Microsoft.Intune_SecurityTasks_Read",
                        "Microsoft.Intune_RemoteTasks_EnableWindowsIntuneAgent",
                        "Microsoft.Intune_TelecomExpenses_Read",
                        "Microsoft.Intune_MobileThreatDefense_Read",
                        "Microsoft.Intune_EndpointProtection_Read",
                        "Microsoft.Intune_AppleDeviceSerialNumbers_Read",
                        "Microsoft.Intune_EndpointAnalytics_Read",
                        "Microsoft.Intune_RemoteTasks_ResetPasscode",
                        "Microsoft.Intune_RemoteTasks_ConfigurationManagerAction",
                        "Microsoft.Intune_CloudAttach_Collections",
                        "Microsoft.Intune_CloudAttach_ResourceExplorer",
                        "Microsoft.Intune_CloudAttach_Timeline",
                        "Microsoft.Intune_DeviceConfigurations_Read",
                        "Microsoft.Intune_CloudAttach_Scripts",
                        "Microsoft.Intune_CloudAttach_SoftwareUpdates",
                        "Microsoft.Intune_OrganizationalMessages_Read",
                        "Microsoft.Intune_RemoteTasks_OnDemandProactiveRemediation",
                        "Microsoft.Intune_MultiAdminApproval_ReadAccessPolicy",
                        "Microsoft.Intune_EpmPolicy_ViewReports",
                        "Microsoft.Intune_TermsAndConditions_Read",
                        "Microsoft.Intune_SecurityBaselines_Read",
                        "Microsoft.Intune_AssignmentFilter_Read",
                        "Microsoft.Intune_CertificateConnector_Read",
                        "Microsoft.Intune_RemoteTasks_EnableLostMode",
                        "Microsoft.Intune_MicrosoftDefenderATP_Read",
                        "Microsoft.Intune_RemoteTasks_RotateLocalAdminPassword",
                        "Microsoft.Intune_EpmPolicy_Read",
                        "Microsoft.Intune_DeviceConfigurations_ViewReports",
                        "Microsoft.Intune_CorporateDeviceIdentifiers_Read",
                        "Microsoft.Intune_MicrosoftTunnelGateway_Read",
                        "Microsoft.Intune_RemoteTasks_DeviceLogs",
                        "Microsoft.Intune_RemoteTasks_PlayLostModeSound",
                        "Microsoft.Intune_RemoteTasks_RebootNow",
                        "Microsoft.Intune_RemoteTasks_RotateFileVaultKey",
                        "Microsoft.Intune_RemoteTasks_SyncDevice",
                        "Microsoft.Intune_MicrosoftStoreForBusiness_Read",
                        "Microsoft.Intune_ManagedGooglePlay_Read",
                        "Microsoft.Intune_AndroidFota_Read",
                        "Microsoft.Intune_QuietTimePolicies_Read",
                        "Microsoft.Intune_CloudAttach_CMPivot",
                        "Microsoft.Intune_WindowsEnterpriseCertificate_Read",
                        "Microsoft.Intune_MobileApps_ViewReports",
                        "Microsoft.Intune_RemoteAssistance_Read",
                        "Microsoft.Intune_DeviceEnrollmentManagers_Read",
                        "Microsoft.Intune_ManagedDevices_ViewReports",
                        "Microsoft.Intune_QuietTimePolicies_ViewReports",
                        "Microsoft.Intune_CloudAttach_ClientDetails",
                        "Microsoft.Intune_CloudAttach_ApplicationActions",
                        "Microsoft.Intune_CloudAttach_Applications",
                        "Microsoft.Intune_CloudAttach_EnrollNow",
                    ],
                    "notAllowedResourceActions": []
                }
            ]
        }
    ],
    "rolePermissions": [
        {
            "actions": [
                "Microsoft.Intune_AndroidSync_Read",
                "Microsoft.Intune_MobileApps_Read",
                "Microsoft.Intune_ManagedApps_Read",
                "Microsoft.Intune_PolicySets_Read",
                "Microsoft.Intune_Reports_Read",
                "Microsoft.Intune_Customization_Read",
                "Microsoft.Intune_Organization_Read",
                "Microsoft.Intune_ManagedDevices_Read",
                "Microsoft.Intune_RemoteTasks_GetFileVaultKey",
                "Microsoft.Intune_RemoteTasks_WindowsDefender",
                "Microsoft.Intune_RemoteTasks_ManageSharedDeviceUsers",
                "Microsoft.Intune_DeviceCompliancePolices_Read",
                "Microsoft.Intune_AppleEnrollmentProfiles_Read",
                "Microsoft.Intune_PartnerDeviceManagement_Read",
                "Microsoft.Intune_EnrollmentProgramToken_Read",
                "Microsoft.Intune_RemoteTasks_DisableLostMode",
                "Microsoft.Intune_RemoteTasks_RotateBitLockerKeys",
                "Microsoft.Intune_Roles_Read",
                "Microsoft.Intune_RemoteAssistance_ViewReports",
                "Microsoft.Intune_DeviceCompliancePolices_ViewReports",
                "Microsoft.Intune_ChromebookSync_Read",
                "Microsoft.Intune_RemoteTasks_ShutDown",
                "Microsoft.Intune_DerivedCredentials_Read",
                "Microsoft.Intune_RemoteTasks_LocateDevice",
                "Microsoft.Intune_RemoteTasks_RemoteLock",
                "Microsoft.Intune_ManagedDevices_SetPrimaryUser",
                "Microsoft.Intune_SecurityTasks_Read",
                "Microsoft.Intune_RemoteTasks_EnableWindowsIntuneAgent",
                "Microsoft.Intune_TelecomExpenses_Read",
                "Microsoft.Intune_MobileThreatDefense_Read",
                "Microsoft.Intune_EndpointProtection_Read",
                "Microsoft.Intune_AppleDeviceSerialNumbers_Read",
                "Microsoft.Intune_EndpointAnalytics_Read",
                "Microsoft.Intune_RemoteTasks_ResetPasscode",
                "Microsoft.Intune_RemoteTasks_ConfigurationManagerAction",
                "Microsoft.Intune_CloudAttach_Collections",
                "Microsoft.Intune_CloudAttach_ResourceExplorer",
                "Microsoft.Intune_CloudAttach_Timeline",
                "Microsoft.Intune_DeviceConfigurations_Read",
                "Microsoft.Intune_CloudAttach_Scripts",
                "Microsoft.Intune_CloudAttach_SoftwareUpdates",
                "Microsoft.Intune_OrganizationalMessages_Read",
                "Microsoft.Intune_RemoteTasks_OnDemandProactiveRemediation",
                "Microsoft.Intune_MultiAdminApproval_ReadAccessPolicy",
                "Microsoft.Intune_EpmPolicy_ViewReports",
                "Microsoft.Intune_TermsAndConditions_Read",
                "Microsoft.Intune_SecurityBaselines_Read",
                "Microsoft.Intune_AssignmentFilter_Read",
                "Microsoft.Intune_CertificateConnector_Read",
                "Microsoft.Intune_RemoteTasks_EnableLostMode",
                "Microsoft.Intune_MicrosoftDefenderATP_Read",
                "Microsoft.Intune_RemoteTasks_RotateLocalAdminPassword",
                "Microsoft.Intune_EpmPolicy_Read",
                "Microsoft.Intune_DeviceConfigurations_ViewReports",
                "Microsoft.Intune_CorporateDeviceIdentifiers_Read",
                "Microsoft.Intune_MicrosoftTunnelGateway_Read",
                "Microsoft.Intune_RemoteTasks_DeviceLogs",
                "Microsoft.Intune_RemoteTasks_PlayLostModeSound",
                "Microsoft.Intune_RemoteTasks_RebootNow",
                "Microsoft.Intune_RemoteTasks_RotateFileVaultKey",
                "Microsoft.Intune_RemoteTasks_SyncDevice",
                "Microsoft.Intune_MicrosoftStoreForBusiness_Read",
                "Microsoft.Intune_ManagedGooglePlay_Read",
                "Microsoft.Intune_AndroidFota_Read",
                "Microsoft.Intune_QuietTimePolicies_Read",
                "Microsoft.Intune_CloudAttach_CMPivot",
                "Microsoft.Intune_WindowsEnterpriseCertificate_Read",
                "Microsoft.Intune_MobileApps_ViewReports",
                "Microsoft.Intune_RemoteAssistance_Read",
                "Microsoft.Intune_DeviceEnrollmentManagers_Read",
                "Microsoft.Intune_ManagedDevices_ViewReports",
                "Microsoft.Intune_QuietTimePolicies_ViewReports",
                "Microsoft.Intune_CloudAttach_ClientDetails",
                "Microsoft.Intune_CloudAttach_ApplicationActions",
                "Microsoft.Intune_CloudAttach_Applications",
                "Microsoft.Intune_CloudAttach_EnrollNow",
            ],
            "resourceActions": [
                {
                    "allowedResourceActions": [
                        "Microsoft.Intune_AndroidSync_Read",
                        "Microsoft.Intune_MobileApps_Read",
                        "Microsoft.Intune_ManagedApps_Read",
                        "Microsoft.Intune_PolicySets_Read",
                        "Microsoft.Intune_Reports_Read",
                        "Microsoft.Intune_Customization_Read",
                        "Microsoft.Intune_Organization_Read",
                        "Microsoft.Intune_ManagedDevices_Read",
                        "Microsoft.Intune_RemoteTasks_GetFileVaultKey",
                        "Microsoft.Intune_RemoteTasks_WindowsDefender",
                        "Microsoft.Intune_RemoteTasks_ManageSharedDeviceUsers",
                        "Microsoft.Intune_DeviceCompliancePolices_Read",
                        "Microsoft.Intune_AppleEnrollmentProfiles_Read",
                        "Microsoft.Intune_PartnerDeviceManagement_Read",
                        "Microsoft.Intune_EnrollmentProgramToken_Read",
                        "Microsoft.Intune_RemoteTasks_DisableLostMode",
                        "Microsoft.Intune_RemoteTasks_RotateBitLockerKeys",
                        "Microsoft.Intune_Roles_Read",
                        "Microsoft.Intune_RemoteAssistance_ViewReports",
                        "Microsoft.Intune_DeviceCompliancePolices_ViewReports",
                        "Microsoft.Intune_ChromebookSync_Read",
                        "Microsoft.Intune_RemoteTasks_ShutDown",
                        "Microsoft.Intune_DerivedCredentials_Read",
                        "Microsoft.Intune_RemoteTasks_LocateDevice",
                        "Microsoft.Intune_RemoteTasks_RemoteLock",
                        "Microsoft.Intune_ManagedDevices_SetPrimaryUser",
                        "Microsoft.Intune_SecurityTasks_Read",
                        "Microsoft.Intune_RemoteTasks_EnableWindowsIntuneAgent",
                        "Microsoft.Intune_TelecomExpenses_Read",
                        "Microsoft.Intune_MobileThreatDefense_Read",
                        "Microsoft.Intune_EndpointProtection_Read",
                        "Microsoft.Intune_AppleDeviceSerialNumbers_Read",
                        "Microsoft.Intune_EndpointAnalytics_Read",
                        "Microsoft.Intune_RemoteTasks_ResetPasscode",
                        "Microsoft.Intune_RemoteTasks_ConfigurationManagerAction",
                        "Microsoft.Intune_CloudAttach_Collections",
                        "Microsoft.Intune_CloudAttach_ResourceExplorer",
                        "Microsoft.Intune_CloudAttach_Timeline",
                        "Microsoft.Intune_DeviceConfigurations_Read",
                        "Microsoft.Intune_CloudAttach_Scripts",
                        "Microsoft.Intune_CloudAttach_SoftwareUpdates",
                        "Microsoft.Intune_OrganizationalMessages_Read",
                        "Microsoft.Intune_RemoteTasks_OnDemandProactiveRemediation",
                        "Microsoft.Intune_MultiAdminApproval_ReadAccessPolicy",
                        "Microsoft.Intune_EpmPolicy_ViewReports",
                        "Microsoft.Intune_TermsAndConditions_Read",
                        "Microsoft.Intune_SecurityBaselines_Read",
                        "Microsoft.Intune_AssignmentFilter_Read",
                        "Microsoft.Intune_CertificateConnector_Read",
                        "Microsoft.Intune_RemoteTasks_EnableLostMode",
                        "Microsoft.Intune_MicrosoftDefenderATP_Read",
                        "Microsoft.Intune_RemoteTasks_RotateLocalAdminPassword",
                        "Microsoft.Intune_EpmPolicy_Read",
                        "Microsoft.Intune_DeviceConfigurations_ViewReports",
                        "Microsoft.Intune_CorporateDeviceIdentifiers_Read",
                        "Microsoft.Intune_MicrosoftTunnelGateway_Read",
                        "Microsoft.Intune_RemoteTasks_DeviceLogs",
                        "Microsoft.Intune_RemoteTasks_PlayLostModeSound",
                        "Microsoft.Intune_RemoteTasks_RebootNow",
                        "Microsoft.Intune_RemoteTasks_RotateFileVaultKey",
                        "Microsoft.Intune_RemoteTasks_SyncDevice",
                        "Microsoft.Intune_MicrosoftStoreForBusiness_Read",
                        "Microsoft.Intune_ManagedGooglePlay_Read",
                        "Microsoft.Intune_AndroidFota_Read",
                        "Microsoft.Intune_QuietTimePolicies_Read",
                        "Microsoft.Intune_CloudAttach_CMPivot",
                        "Microsoft.Intune_WindowsEnterpriseCertificate_Read",
                        "Microsoft.Intune_MobileApps_ViewReports",
                        "Microsoft.Intune_RemoteAssistance_Read",
                        "Microsoft.Intune_DeviceEnrollmentManagers_Read",
                        "Microsoft.Intune_ManagedDevices_ViewReports",
                        "Microsoft.Intune_QuietTimePolicies_ViewReports",
                        "Microsoft.Intune_CloudAttach_ClientDetails",
                        "Microsoft.Intune_CloudAttach_ApplicationActions",
                        "Microsoft.Intune_CloudAttach_Applications",
                        "Microsoft.Intune_CloudAttach_EnrollNow",
                    ],
                    "notAllowedResourceActions": []
                }
            ]
        }
    ]
    }
'@

# Invoke the Graph request to create the custom Intune role
Invoke-MgGraphRequest -Uri $uri -body $json -Method POST -ContentType "application/json"