Select DISTINCT SYS.Netbios_Name0,SYS.Resource_Domain_OR_Workgr0,SP.CompanyName, SP.ProductName, SP.ProductVersion
FROM v_GS_SoftwareProduct SP
JOIN v_R_System SYS ON SP.ResourceID=SYS.ResourceID
JOIN v_FullCollectionMembership fcm on sys.ResourceID=fcm.ResourceID 
WHERE fcm.CollectionID = 'SMS00000'
AND SP.CompanyName NOT LIKE '3ivx'
AND SP.CompanyName != '3M'
AND SP.CompanyName NOT LIKE 'AAOS'
AND SP.CompanyName != 'Abbott Labs'
AND SP.CompanyName != 'Acro Software Inc.'
AND SP.CompanyName != 'Adobe Systems'
AND SP.CompanyName NOT LIKE 'AdoptOpenJDK'
AND SP.CompanyName NOT LIKE 'Advanced Micro Devices'
AND SP.CompanyName != 'Ahead Software'
AND SP.CompanyName != 'akeo.ie'
AND SP.CompanyName != 'Akeo Consulting'
AND SP.CompanyName != 'Alexander Roshal'
AND SP.CompanyName NOT LIKE 'Alps%'
AND SP.CompanyName NOT LIKE 'Altiris'
AND SP.CompanyName NOT LIKE 'Amazon%'
AND SP.CompanyName NOT LIKE 'Ambir Technology'
AND SP.CompanyName NOT LIKE 'Ambir Technology, Inc.'
AND SP.CompanyName NOT LIKE 'Amtelco'
AND SP.CompanyName NOT LIKE 'Anaconda'
AND SP.CompanyName NOT LIKE 'Angry IP'
AND SP.CompanyName != 'angryip.org'
AND SP.CompanyName NOT LIKE 'Antibody'
AND SP.CompanyName NOT LIKE 'AO Kaspersky'
AND SP.CompanyName NOT LIKE 'APOWERSOFT LIMITED'
AND SP.CompanyName NOT LIKE 'Apple'
AND SP.CompanyName NOT LIKE 'Arctic Wolf%'
AND SP.CompanyName NOT LIKE 'Artifex Software'
AND SP.CompanyName NOT LIKE 'ASCENSIA'
AND SP.CompanyName NOT LIKE 'Asmedia Technology'
AND SP.CompanyName != 'AT&T'
AND SP.CompanyName NOT LIKE 'Atlas Business Solutions'
AND SP.CompanyName != 'Audacity Team'
AND SP.CompanyName != 'AuthenTec'
AND SP.CompanyName != 'AuthenTec, Inc.'
AND SP.CompanyName NOT LIKE 'Autodesk'
AND SP.CompanyName != 'AutoHotkey'
AND SP.CompanyName != 'AutoIt Team'
AND SP.CompanyName != 'Avast Software'
AND SP.CompanyName NOT LIKE 'Axis Communications'
AND SP.CompanyName NOT LIKE 'Barracuda Networks'
AND SP.CompanyName NOT LIKE 'Bartels Media GmbH'
AND SP.CompanyName != 'Bitdefender'
AND SP.CompanyName != 'BitDefender S.R.L.'
AND SP.CompanyName NOT LIKE 'BioEx'
AND SP.CompanyName NOT LIKE 'Biscom%'
AND SP.CompanyName != 'Bluebeam, Inc.'
AND SP.CompanyName != 'Bluebeam Software, Inc.'
AND SP.CompanyName != 'Blue Jeans'
AND SP.CompanyName != 'BlueJeans'
AND SP.CompanyName != 'BlueJeans Network'
AND SP.CompanyName != 'BlueJeans Network, Inc.'
AND SP.CompanyName NOT LIKE 'BlueStack'
AND SP.CompanyName != 'Bomgar'
AND SP.CompanyName != 'Box'
AND SP.CompanyName NOT LIKE 'brackets.io'
AND SP.CompanyName != 'Broadcom'
AND SP.CompanyName NOT LIKE 'Brother Industries'
AND SP.CompanyName NOT LIKE 'Calabrio'
AND SP.CompanyName NOT LIKE '%Canon%'
AND SP.CompanyName NOT LIKE 'Carbon Black'
AND SP.CompanyName NOT LIKE 'Card Scanning Solutions'
AND SP.CompanyName NOT LIKE 'CData Software'
AND SP.CompanyName != 'Cedars-Sinai Medical Center'
AND SP.CompanyName != 'Cedars-Sinai Medical Center :: AIM Program'
AND SP.CompanyName NOT LIKE 'Change Healthcare'
AND SP.CompanyName != 'Charles Schwab & Co., Inc.'
AND SP.CompanyName != 'Cinematronics'
AND SP.CompanyName NOT LIKE 'Cireson'
AND SP.CompanyName NOT LIKE 'Cisco%'
AND SP.CompanyName NOT LIKE 'Citrix%'
AND SP.CompanyName != 'Cohesity Inc.'
AND SP.CompanyName NOT LIKE 'Conexant%'
AND SP.CompanyName NOT LIKE 'Control Solutions'
AND SP.CompanyName != 'Core FTP'
And SP.CompanyName != 'Corel'
AND SP.CompanyName != 'Corsair Memory, Inc.'
AND SP.CompanyName NOT LIKE 'CSMC Cardiac Suite'
AND SP.CompanyName NOT LIKE 'CyberLink'
AND SP.CompanyName NOT LIKE 'D-Link'
AND SP.CompanyName NOT LIKE 'Data Innovations'
AND SP.CompanyName NOT LIKE 'Datawatch'
AND SP.CompanyName != 'Delivered by Citrix'
AND SP.CompanyName != 'Dell'
AND SP.CompanyName != 'Dell Computer'
AND SP.CompanyName != 'Design Science'
AND SP.CompanyName NOT LIKE 'Developer-Diamond Software Systems'
AND SP.CompanyName NOT LIKE 'Dexcom'
AND SP.CompanyName != 'digiChart, Inc.'
AND SP.CompanyName NOT LIKE 'DigitalShipper'
AND SP.CompanyName != 'Discord Inc.'
AND SP.CompanyName NOT LIKE 'DisplayLink%'
AND SP.CompanyName NOT LIKE 'Dominik Reichl'
AND SP.CompanyName != 'Don HO don.h@free.fr'
AND SP.CompanyName NOT LIKE 'DR Systems'
AND SP.CompanyName != 'Dropbox, Inc.'
AND SP.CompanyName != 'DYMO'
AND SP.CompanyName NOT LIKE 'Ecovate'
AND SP.CompanyName != 'EDCO'
AND SP.CompanyName != 'EDCO ® Health Information Solutions'
AND SP.CompanyName != 'EDCO Group, Inc.'
AND SP.CompanyName NOT LIKE 'Elo Touch'
AND SP.CompanyName NOT LIKE 'EMC'
AND SP.CompanyName NOT LIKE 'eMix'
AND SP.CompanyName NOT LIKE 'Epson'
AND SP.CompanyName != 'Euro Plus d.o.o.'
AND SP.CompanyName NOT LIKE 'Evoluent'
AND SP.CompanyName != 'f.lux Software LLC'
AND SP.CompanyName != 'Facebook'
AND SP.CompanyName NOT LIKE 'Famatech'
AND SP.CompanyName NOT LIKE 'FedEx'
AND SP.CompanyName != 'FileZilla Project'
AND SP.CompanyName != 'Fitbit Inc.'
AND SP.CompanyName != 'Fitbit, Inc.'
AND SP.CompanyName != 'Flexera'
AND SP.CompanyName != 'Flexera Software'
AND SP.CompanyName != 'Flexera Software LLC'
AND SP.CompanyName != 'Flexera Software LLC.'
AND SP.CompanyName != 'Flexera Software, Inc.'
AND SP.CompanyName != 'Fluke Corporation'
AND SP.CompanyName != 'FMAudit'
AND SP.CompanyName NOT LIKE 'Foolish%'
AND SP.CompanyName != 'Foxit'
AND SP.CompanyName != 'Foxit Corporation'
AND SP.CompanyName != 'Foxit Software'
AND SP.CompanyName != 'Foxit Software Company'
AND SP.CompanyName != 'Foxit Software Inc.'
AND SP.CompanyName NOT LIKE 'FTDI Ltd'
AND SP.CompanyName NOT LIKE 'Fujitsu'
AND SP.CompanyName NOT LIKE 'Fuze'
AND SP.CompanyName NOT LIKE 'Gadwin Systems'
AND SP.CompanyName != 'Garmin Ltd or its subsidiaries'
AND SP.CompanyName != 'Garmin Ltd. or its subsidiaries'
AND SP.CompanyName NOT LIKE 'GE%'
AND SP.CompanyName NOT LIKE 'General Electric%'
AND SP.CompanyName NOT LIKE 'Ghostgum Software'
AND SP.CompanyName != 'GitHub'
AND SP.CompanyName != 'GitHub, Inc.'
AND SP.CompanyName != 'GitHub.UI'
AND SP.CompanyName != 'GlavSoft LLC.'
AND SP.CompanyName NOT LIKE 'gMed'
AND SP.CompanyName NOT LIKE 'Goodix'
AND SP.CompanyName NOT LIKE 'Google%'
AND SP.CompanyName NOT LIKE 'GoPro'
AND SP.CompanyName NOT LIKE 'Grafana'
AND SP.CompanyName NOT LIKE 'Grammarly'
AND SP.CompanyName != 'Greenshot'
AND SP.CompanyName NOT LIKE 'Hamrick Software'
AND SP.CompanyName NOT LIKE 'Harman'
AND SP.CompanyName NOT LIKE 'Helios'
AND SP.CompanyName != 'Health Informatics Technologies,  L.L.C.'
AND SP.CompanyName NOT LIKE 'HealthPort'
AND SP.CompanyName != 'Helge Klein'
AND SP.CompanyName != 'Hewlett Packard'
AND SP.CompanyName != 'Hewlett-Packard'
AND SP.CompanyName != 'HP'
AND SP.CompanyName != 'Hygiena'
AND SP.CompanyName != 'Hygiena LLC'
AND SP.CompanyName != 'Ignite Realtime'
AND SP.CompanyName NOT LIKE 'Igor Pavlov'
AND SP.CompanyName != 'ImageMaker Inc.  Written by Peter Gron, Raincoast Software, ltd.'
AND SP.CompanyName NOT LIKE 'Imprivata%'
AND SP.CompanyName != 'Indigo Rose'
AND SP.CompanyName != 'Ingenico'
AND SP.CompanyName != 'Ingenico Group'
AND SP.CompanyName != 'InstallShield'
AND SP.CompanyName NOT LIKE 'InstaMed'
AND SP.CompanyName NOT LIKE 'Intel'
AND SP.CompanyName NOT LIKE 'InterCall'
AND SP.CompanyName NOT LIKE 'Intuit'
AND SP.CompanyName NOT LIKE 'John MacFarlane'
AND SP.CompanyName NOT LIKE 'Kai Kramer'
AND SP.CompanyName != 'Kensington Group, a division of ACCO Brands'
AND SP.CompanyName != 'Kensington, a division of ACCO Brands'
AND SP.CompanyName NOT LIKE 'Keyspan'
AND SP.CompanyName NOT LIKE 'KnowBe4 Inc.'
AND SP.CompanyName != 'Kofax Communications, Inc.'
AND SP.CompanyName != 'Kofax Inc.'
AND SP.CompanyName != 'Kofax, Inc.'
AND SP.CompanyName != 'Kofax.'
AND SP.CompanyName != 'KONICA MINOLTA'
AND SP.CompanyName != 'KONICA MINOLTA, INC'
AND SP.CompanyName != 'KONICA MINOLTA, INC.'
AND SP.CompanyName != 'LANDesk Software'
AND SP.CompanyName NOT LIKE 'Lantronix'
AND SP.CompanyName != 'LastPass'
AND SP.CompanyName NOT LIKE 'Lenovo Group'
AND SP.CompanyName NOT LIKE 'Lexikos'
AND SP.CompanyName NOT LIKE 'Lexmark'
AND SP.CompanyName NOT LIKE 'LifeScan'
AND SP.CompanyName NOT LIKE 'Lightning'
AND SP.CompanyName != 'Linoma Software'
AND SP.CompanyName NOT LIKE 'Logitech'
AND SP.CompanyName NOT LIKE 'LogMeIn%'
AND SP.CompanyName != 'LogTag Recorders Limited'
AND SP.CompanyName NOT LIKE 'Lorex'
AND SP.CompanyName != 'LVM Systems'
AND SP.CompanyName NOT LIKE 'M*Modal'
AND SP.CompanyName != 'MagTek'
AND SP.CompanyName != 'MagTek, Inc.'
AND SP.CompanyName NOT LIKE 'Malamute'
AND SP.CompanyName NOT LIKE 'Martin Prikryl'
AND SP.CompanyName NOT LIKE 'Matrox Imaging'
AND SP.CompanyName != 'Mead & Co'
AND SP.CompanyName != 'Mead & Co Limited'
AND SP.CompanyName NOT LIKE 'Medical Packaging'
AND SP.CompanyName NOT LIKE 'Medtronic Diabetes'
AND SP.CompanyName NOT LIKE 'MedVantage'
AND SP.CompanyName NOT LIKE '%Microsoft%'
AND SP.CompanyName NOT LIKE 'Mike Ward'
AND SP.CompanyName NOT LIKE 'Milestone Systems'
AND SP.CompanyName NOT LIKE 'MIM Software'
AND SP.CompanyName NOT LIKE 'Minitab'
AND SP.CompanyName NOT LIKE 'Mobatek'
AND SP.CompanyName NOT LIKE 'Mozilla'
AND SP.CompanyName NOT LIKE 'Muratec'
AND SP.CompanyName NOT LIKE 'NA1Messenger'
AND SP.CompanyName NOT LIKE 'NagleCode'
AND SP.CompanyName NOT LIKE 'NASDAQ'
AND SP.CompanyName != 'Nero'
And SP.CompanyName != 'Nero AG'
AND SP.CompanyName != 'Nero, Inc.'
AND SP.CompanyName != 'NetMotion Software, Inc.'
AND SP.CompanyName NOT LIKE 'Netsmart'
AND SP.CompanyName NOT LIKE 'Next Generation Software'
AND SP.CompanyName != 'Newell Rubbermaid'
AND SP.CompanyName NOT LIKE 'NewSoft'
AND SP.CompanyName NOT LIKE 'Nmap Project'
AND SP.CompanyName NOT LIKE 'Node.js'
AND SP.CompanyName NOT LIKE 'NotePad++'
AND SP.CompanyName NOT LIKE 'Now Micro'
AND SP.CompanyName NOT LIKE 'Nuance%'
AND SP.CompanyName NOT LIKE 'NVIDIA'
AND SP.CompanyName NOT LIKE 'Ocenaudio'
AND SP.CompanyName NOT LIKE 'Open Text'
AND SP.CompanyName NOT LIKE 'OpenVPN'
AND SP.CompanyName != 'Opera Software'
AND SP.CompanyName NOT LIKE 'OTiS Medical Analytics'
AND SP.CompanyName NOT LIKE 'Packetizer'
AND SP.CompanyName != 'PFU'
AND SP.CompanyName != 'PFU Limited'
AND SP.CompanyName != 'PFU Limited.'
AND SP.CompanyName != 'PFU Limted'
AND SP.CompanyName NOT LIKE 'PGP Corporation'
AND SP.CompanyName NOT LIKE 'Physio-Control'
AND SP.CompanyName NOT LIKE 'Piriform'
AND SP.CompanyName != 'Plantronics'
AND SP.CompanyName != 'Plantronics, Inc.'
AND SP.CompanyName != 'PortableApps.com'
AND SP.CompanyName NOT LIKE 'PROFOX'
AND SP.CompanyName NOT LIKE 'PSAppDeployToolkit'
AND SP.CompanyName NOT LIKE 'Python'
AND SP.CompanyName NOT LIKE 'Qualcomm'
AND SP.CompanyName NOT LIKE 'R Core Team'
AND SP.CompanyName != 'Razer Inc.'
AND SP.CompanyName NOT LIKE 'Realtek%'
AND SP.CompanyName NOT LIKE 'RealVNC'
AND SP.CompanyName NOT LIKE 'Recast Software'
AND SP.CompanyName NOT LIKE 'ReportServer'
AND SP.CompanyName NOT LIKE 'Riverbed Technology'
AND SP.CompanyName NOT LIKE 'Rivet Networks'
AND SP.CompanyName NOT LIKE 'Robware'
AND SP.CompanyName != 'Roche'
AND SP.CompanyName != 'Roche Diabetes Care, Inc.'
AND SP.CompanyName NOT LIKE 'Samsung Electronics'
AND SP.CompanyName != 'Sanford, L.P.'
AND SP.CompanyName NOT LIKE 'SAStevenson'
AND SP.CompanyName NOT LIKE 'ScanSnap Manager'
AND SP.CompanyName != 'Scooter Software'
AND SP.CompanyName NOT LIKE 'Seiko'
AND SP.CompanyName != 'Sennheiser Communications'
AND SP.CompanyName != 'Sennheiser Communications A/S 2016'
AND SP.CompanyName != 'Sergey Bezruchkin'
AND SP.CompanyName != 'ShareX Team'
AND SP.CompanyName != 'Simon Tatham'
AND SP.CompanyName NOT LIKE 'Skype%'
AND SP.CompanyName != 'Slack Technologies Inc.'
AND SP.CompanyName NOT LIKE 'SMSAgent'
AND SP.CompanyName NOT LIKE 'Softerra'
AND SP.CompanyName != 'Sony'
AND SP.CompanyName NOT LIKE 'SonicWALL'
AND SP.CompanyName NOT LIKE 'Splunk'
And SP.CompanyName != 'Spotify Ltd'
AND SP.CompanyName NOT LIKE 'Star Micronics'
AND SP.CompanyName != 'Stardock'
AND SP.CompanyName != 'Stardock Corporation'
AND SP.CompanyName != 'Stardock Software'
AND SP.CompanyName != 'Stardock Software, Inc'
AND SP.CompanyName NOT LIKE 'Strata Decision Technology'
AND SP.CompanyName NOT LIKE 'SupportSoft'
AND SP.CompanyName NOT LIKE 'Syft'
AND SP.CompanyName NOT LIKE 'Symantec'
AND SP.CompanyName NOT LIKE 'Synaptics'
AND SP.CompanyName NOT LIKE 'Tandem Diabetes Care'
AND SP.CompanyName != 'TeamViewr'
AND SP.CompanyName != 'TeamViewer Germany GmbH'
AND SP.CompanyName != 'TeamViewer GmbH'
AND SP.CompanyName NOT LIKE 'TechSmith%'
AND SP.CompanyName != 'Telerik'
AND SP.CompanyName NOT LIKE 'Tenable'
AND SP.CompanyName NOT LIKE 'TerminalWorks'
AND SP.CompanyName NOT LIKE 'The GIMP Team'
AND SP.CompanyName != 'The Git Development Community'
AND SP.CompanyName NOT LIKE 'The Gpg4win Project'
AND SP.CompanyName NOT LIKE 'The Linux Tn5250 Project'
AND SP.CompanyName NOT LIKE 'The Prometheus Group'
AND SP.CompanyName != 'The Wireshark developer community'
AND SP.CompanyName != 'The Wireshark developer community, https://www.wireshark.org/'
AND SP.CompanyName NOT LIKE 'Tidepool Project'
AND SP.CompanyName != 'TigerText Inc'
AND SP.CompanyName NOT LIKE 'TimeKeeping Systems'
AND SP.CompanyName != 'Tricerat'
AND SP.CompanyName != 'Tricerat, Inc.'
AND SP.CompanyName NOT LIKE 'Trimble'
AND SP.CompanyName != 'UltraVNC'
AND SP.CompanyName NOT LIKE 'UPS'
AND SP.CompanyName NOT LIKE 'United Parcel Service'
AND SP.CompanyName NOT LIKE 'Valve'
AND SP.CompanyName NOT LIKE 'VanDyke Software'
AND SP.CompanyName NOT LIKE 'Varian'
AND SP.CompanyName NOT LIKE 'Viber'
AND SP.CompanyName NOT LIKE 'VideoLAN'
AND SP.CompanyName NOT LIKE 'Visioneer'
AND SP.CompanyName NOT LIKE 'Visual Health Information'
AND SP.CompanyName NOT LIKE 'VMWare'
AND SP.CompanyName != 'Voice Print International'
AND SP.CompanyName != 'Voice Print International, Inc.'
AND SP.CompanyName != 'VPI'
AND SP.CompanyName != 'Voiceprint International, Inc.'
AND SP.CompanyName NOT LIKE 'Vyrty'
AND SP.CompanyName NOT LIKE 'Xvid'
AND SP.CompanyName != 'Wacom Technology, Corp.'
AND SP.CompanyName != 'Waves Audio'
AND SP.CompanyName != 'Waves Audio Ltd'
AND SP.CompanyName != 'Wavesor Software'
AND SP.CompanyName != 'WebEx'
AND SP.CompanyName NOT LIKE 'Welch Allyn'
AND SP.CompanyName != 'Western Digital Technologies, Inc.'
AND SP.CompanyName != 'WhatsApp'
AND SP.CompanyName NOT LIKE 'win.rar GmbH'
AND SP.CompanyName != 'Wireshark development team'
AND SP.CompanyName NOT LIKE 'Wolfram'
AND SP.CompanyName NOT LIKE 'Wondershare'
AND SP.CompanyName NOT LIKE 'WQR'
AND SP.CompanyName NOT LIKE 'Xamarin'
AND SP.CompanyName != 'Xvid Team'
AND SP.CompanyName NOT LIKE 'Yahoo'
AND SP.CompanyName NOT LIKE 'Yubico'
AND SP.CompanyName NOT LIKE 'Zander Tools'
AND SP.CompanyName != 'Zebra\Status Monitor'
AND SP.CompanyName != 'Zebra Technologies'
AND SP.CompanyName NOT LIKE 'Zoom%'
AND SP.ProductName NOT LIKE 'ACE'
AND SP.ProductName NOT LIKE 'Acrobat X Suite'
AND SP.ProductName NOT LIKE 'Acuant SDK'
AND SP.ProductName NOT LIKE 'AcuFill SDK'
AND SP.ProductName NOT LIKE 'Adesso Camera'
AND SP.ProductName NOT LIKE 'Adesso Cybertrack Driver'
AND SP.ProductName NOT LIKE 'AeroScout Engine Manager'
AND SP.ProductName NOT LIKE 'Allscripts Care Management'
AND SP.ProductName NOT LIKE 'Amtelco Voice'
AND SP.ProductName NOT LIKE 'AnzioWin'
AND SP.ProductName NOT LIKE 'api LaborWorkx%'
AND SP.ProductName NOT LIKE 'ApneaLink'
AND SP.ProductName NOT LIKE 'AutoIt'
AND SP.ProductName NOT LIKE 'AWS Command Line'
AND SP.ProductName NOT LIKE 'Blackboard Collaborate Launcher'
AND SP.ProductName NOT LIKE 'Borland Data Engine'
AND SP.ProductName NOT LIKE 'CapturePerfect'
AND SP.ProductName NOT LIKE 'Cardio Workflow Client'
AND SP.ProductName NOT LIKE 'CBORD Food and Nutrition Service Suite'
AND SP.ProductName NOT LIKE 'Computer Info ActiveX'
AND SP.ProductName NOT LIKE 'COVID-19 Interpretive Software'
AND SP.ProductName NOT LIKE 'CPUID'
AND SP.ProductName NOT LIKE 'CRRuntime_12_x86'
AND SP.ProductName NOT LIKE 'CryptoPrevent%'
AND SP.ProductName NOT LIKE 'Crystal .NET'
AND SP.ProductName NOT LIKE 'Crystal Reports'
AND SP.ProductName NOT LIKE 'CutePDF'
AND SP.ProductName NOT LIKE 'CVE-'
AND SP.ProductName NOT LIKE 'Daily QA'
AND SP.ProductName NOT LIKE 'DB Browser for SQLite'
AND SP.ProductName NOT LIKE 'Devart dotConnect for SQLite Standard'
AND SP.ProductName NOT LIKE 'Driver_64'
AND SP.ProductName NOT LIKE 'DYMO'
AND SP.ProductName NOT LIKE 'EditScript MT'
AND SP.ProductName NOT LIKE 'eFilm Workstation'
AND SP.ProductName NOT LIKE 'Exciter Detector'
AND SP.ProductName NOT LIKE 'Exciter Manager'
AND SP.ProductName NOT LIKE 'FileZilla'
AND SP.ProductName != 'BIG-IP Edge Components Troubleshooting'
AND SP.ProductName != 'BIG-IP® Edge Client™'
AND SP.ProductName NOT LIKE 'FreeStyle'
AND SP.ProductName NOT LIKE 'FUJITSU Scanner USB HotFix'
AND SP.ProductName NOT LIKE 'GateWorks'
AND SP.ProductName NOT LIKE 'Guardrails'
AND SP.ProductName NOT LIKE 'Hardware Manager'
AND SP.ProductName NOT LIKE 'HCWP Web Components'
AND SP.ProductName NOT LIKE 'HealthSourceTrayAppInstaller'
AND SP.ProductName NOT LIKE 'HiT ODBC'
AND SP.ProductName NOT LIKE 'Home Diagnostics'
AND SP.ProductName NOT LIKE 'Honeywell InterDriver'
AND SP.ProductName NOT LIKE 'Honeywell Software Downloader'
AND SP.ProductName NOT LIKE 'HorizonClient'
AND SP.ProductName NOT LIKE 'HP Color LaserJet'
AND SP.ProductName NOT LIKE 'HP LaserJet Professional'
AND SP.ProductName NOT LIKE 'HP Officejet Pro'
AND SP.ProductName NOT LIKE 'HP Software Update'
AND SP.ProductName NOT LIKE 'HPSSupply'
AND SP.ProductName NOT LIKE 'hpStatusAlerts'
AND SP.ProductName NOT LIKE 'iBackup'
AND SP.ProductName NOT LIKE 'IBM MQ'
AND SP.ProductName NOT LIKE 'IBM WebSphere'
AND SP.ProductName NOT LIKE 'IP Setup Program'
AND SP.ProductName NOT LIKE 'IIS Express Application'
AND SP.ProductName NOT LIKE 'Ikm Control Downloader'
AND SP.ProductName NOT LIKE 'Infinity OnCall'
AND SP.ProductName NOT LIKE 'InSite Agent'
AND SP.ProductName NOT LIKE 'InstantAccess'
AND SP.ProductName NOT LIKE 'Instant Notifier'
AND SP.ProductName NOT LIKE 'iNTERFACEWARE'
AND SP.ProductName NOT LIKE 'InterMapper RemoteAcces'
AND SP.ProductName NOT LIKE 'InterVideo'
AND SP.ProductName NOT LIKE 'IPMIView'
AND SP.ProductName NOT LIKE 'Ixia'
AND SP.ProductName != 'Java Auto Updater'
AND SP.ProductName != 'Java Platform SE Auto Updater'
AND SP.ProductName NOT LIKE 'KEDIT for Windows 1.6.1'
AND SP.ProductName NOT LIKE 'Latitude Link'
AND SP.ProductName NOT LIKE 'Launch Pad'
AND SP.ProductName NOT LIKE 'Legacy Browser Component'
AND SP.ProductName NOT LIKE 'Lenel AppContext Common Component'
AND SP.ProductName != 'LibreOffice'
AND SP.ProductName NOT LIKE 'LibreView'
AND SP.ProductName NOT LIKE 'MagView'
AND SP.ProductName NOT LIKE 'Maine Standards Data Reduction'
AND SP.ProductName NOT LIKE 'McKesson CSOS'
AND SP.ProductName NOT LIKE 'MCRIF32 - Hospital'
AND SP.ProductName NOT LIKE 'Meditech'
AND SP.ProductName NOT LIKE 'Merge OrthoCase'
AND SP.ProductName NOT LIKE 'Merge PACS Workstation'
AND SP.ProductName NOT LIKE 'Microsoft .NET'
AND SP.ProductName NOT LIKE 'Microsoft Edge'
AND SP.ProductName NOT LIKE 'Microsoft SQL'
AND SP.ProductName NOT LIKE 'Microsoft Visual C++'
AND SP.ProductName NOT LIKE 'Microsoft_VC'
AND SP.ProductName NOT LIKE 'Microsoft Windows Media Video'
AND SP.ProductName NOT LIKE 'MILT4'
AND SP.ProductName NOT LIKE 'Mobile Hotspot Admin'
AND SP.ProductName NOT LIKE 'MrvlUsgTracking64'
AND SP.ProductName NOT LIKE 'mv_encrypt_setup'
AND SP.ProductName NOT LIKE 'nVision'
AND SP.ProductName NOT LIKE 'OBS Studio'
AND SP.ProductName NOT LIKE 'Omnigo Software Dispatch'
AND SP.ProductName NOT LIKE 'OmniLab Direct'
AND SP.ProductName NOT LIKE 'OnGuard'
AND SP.ProductName NOT LIKE 'Online Plug-in'
AND SP.ProductName NOT LIKE 'Oracle Data Provider'
AND SP.ProductName NOT LIKE 'Oracle VM VirtualBox'
AND SP.ProductName NOT LIKE 'PAI Software Portfolio'
AND SP.ProductName NOT LIKE 'PDF Settings'
AND SP.ProductName NOT LIKE 'PDF-XChange 3'
AND SP.ProductName NOT LIKE 'Pdf995'
AND SP.ProductName NOT LIKE 'pdfFactory'
AND SP.ProductName NOT LIKE 'PharmGuard'
AND SP.ProductName NOT LIKE 'Philips Device Control Center'
AND SP.ProductName NOT LIKE 'Philips IntelliSpace'
AND SP.ProductName NOT LIKE 'Philips Respironics Care'
AND SP.ProductName NOT LIKE 'Photoshop'
AND SP.ProductName NOT LIKE 'Print-2-Image'
AND SP.ProductName NOT LIKE 'ProDiver'
AND SP.ProductName NOT LIKE 'psqlODBC'
AND SP.ProductName NOT LIKE 'psqlODBC_x64'
AND SP.ProductName NOT LIKE 'quality_indicators_with_apr_x64'
AND SP.ProductName NOT LIKE 'QWS3270 Freeware'
AND SP.ProductName NOT LIKE 'RadiAnt DICOM'
AND SP.ProductName NOT LIKE 'RAPIDComm'
AND SP.ProductName NOT LIKE 'RHT10'
AND SP.ProductName NOT LIKE 'RightFax%'
AND SP.ProductName NOT LIKE 'Royal TS'
AND SP.ProductName NOT LIKE 'Sandman Elite'
AND SP.ProductName NOT LIKE 'SAP Crystal Reports'
AND SP.ProductName NOT LIKE 'Scanner Utility for Microsoft Windows'
AND SP.ProductName NOT LIKE 'ScanSnap Manager'
AND SP.ProductName NOT LIKE 'Scansoft PDF Professional'
AND SP.ProductName NOT LIKE 'Self-service Plug-in'
AND SP.ProductName NOT LIKE 'Silicon Laboratories USBXpress Device'
AND SP.ProductName NOT LIKE 'Simon Tatham'
AND SP.ProductName NOT LIKE 'Spirometry PC Software'
AND SP.ProductName NOT LIKE 'SNC toolbox'
AND SP.ProductName NOT LIKE 'Software Operation Panel'
AND SP.ProductName NOT LIKE 'Spacelabs Healthcare'
AND SP.ProductName NOT LIKE 'SQLite ODBC Driver'
AND SP.ProductName NOT LIKE 'SSIInstallation'
AND SP.ProductName NOT LIKE 'StruxureWare'
AND SP.ProductName NOT LIKE 'Suite Shared Configuration'
AND SP.ProductName NOT LIKE 'Surveyor/400'
AND SP.ProductName NOT LIKE 'Tableau'
AND SP.ProductName NOT LIKE 'Tag Manager'
AND SP.ProductName NOT LIKE 'TASS'
AND SP.ProductName NOT LIKE 'TED Device Manager'
AND SP.ProductName NOT LIKE 'Tftpd64 Standalone Edition'
AND SP.ProductName NOT LIKE 'thinkorswim'
AND SP.ProductName NOT LIKE 'TrayApp-prerequisite from CIOX'
AND SP.ProductName NOT LIKE 'TRUEmanager Diabetes Management'
AND SP.ProductName NOT LIKE 'UltraView Software Development Kit'
AND SP.ProductName NOT LIKE 'Unified Reports'
AND SP.ProductName NOT LIKE 'Unity Real Time'
AND SP.ProductName NOT LIKE 'US Exciter Configurator'
AND SP.ProductName NOT LIKE 'USB Interface Cradle Driver'
AND SP.ProductName NOT LIKE 'VCRedist'
AND SP.ProductName NOT LIKE 'VersaCare'
AND SP.ProductName NOT LIKE 'VPI'
AND SP.ProductName NOT LIKE 'Vulkan'
AND SP.ProductName NOT LIKE 'Web Components'
AND SP.ProductName NOT LIKE 'Webex'
AND SP.ProductName NOT LIKE 'WIN32 CAL Client'
AND SP.ProductName NOT LIKE 'WinSshBootstrapper'
AND SP.ProductName NOT LIKE 'WinZip'
AND SP.ProductName NOT LIKE 'Windows Driver Package'
AND SP.ProductName NOT LIKE 'Windows Media'
AND SP.ProductName NOT LIKE 'Workbench'
AND SP.ProductName NOT LIKE 'Xerox'
AND SP.ProductName NOT LIKE 'xReminder Pro'
AND SP.ProductName NOT LIKE 'Xltek IPELA Filters' 
ORDER By SP.ProductName, SP.CompanyName, SP.ProductVersion, SYS.Netbios_Name0
